version: '3'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "j0bsh4ngf1r3!"
      ACCEPT_EULA: "Y"